### ISSUE TITLE
下载失败，版本1.2.6

### ISSUE THREAD

**Issue by jie-neng** [FlySelfLog/downkyi#1]
![image](https://user-images.githubusercontent.com/58629010/103147712-f1a74280-4792-11eb-8bc4-5f47a91b0d92.png)

**Comment by jie-neng** [comment]
![NB3XY784X@} LS1S7)J01V](https://user-images.githubusercontent.com/58629010/103147776-68444000-4793-11eb-85a4-90c403f5c3e9.png)

**Comment by tomatoli** [comment]
一样

**Comment by FlySelfLog** [comment]
视频的url贴一下吧

**Comment by jie-neng** [comment]
https://www.bilibili.com/video/BV1nJ411V7bd?p=151

**Comment by FlySelfLog** [comment]
![Snipaste_2020-12-26_22-03-01](https://user-images.githubusercontent.com/19290097/103152947-cb4fca00-47c7-11eb-964b-a2a87a60d458.png)
![Snipaste_2020-12-26_22-12-05](https://user-images.githubusercontent.com/19290097/103152949-cee35100-47c7-11eb-8a27-ba5787dda603.png)

**Comment by FlySelfLog** [comment]
我这里测试是能够正常下载的，版本是v1.3.0 beta，设置同时下载数为3，最大线程数为5，优先下载编码h.265；有可能是你设置的同时下载数过大造成解析失败。

**Comment by jie-neng** [comment]
同时下载1个视频，还是失败了.
有时候解析有点问题吧？画质和解码是空的选项，如图

![ZF 0NAM$IA4N584UNL05E88](https://user-images.githubusercontent.com/58629010/103154024-e9212d00-47cf-11eb-9d33-44c351d4b0bf.png)

**Comment by FlySelfLog** [comment]
> 同时下载1个视频，还是失败了.
> 有时候解析有点问题吧？画质和解码是空的选项，如图
> 
> ![ZF 0NAM$IA4N584UNL05E88](https://user-images.githubusercontent.com/58629010/103154024-e9212d00-47cf-11eb-9d33-44c351d4b0bf.png)
> 

更新到v1.3.0 beta再试试吧

**Comment by likeya** [comment]
同样的问题反馈，更新到最新版v1.3.0 beta后，下载解析均失败，一直处于循环解析且都失败。在1.26版本正常。望修复，谢谢！

**Comment by FlySelfLog** [comment]
> 同样的问题反馈，更新到最新版v1.3.0 beta后，下载解析均失败，一直处于循环解析且都失败。在1.26版本正常。望修复，谢谢！

视频url是多少？是在详情页无法解析出视频列表，还是开始下载后失败？

**Comment by Chopin-9** [comment]
更新到最新版本v1.3.0 beta后视频解析失败 https://www.bilibili.com/video/BV1wi4y1V7rT?t=14&p=78

**Comment by jie-neng** [comment]
实测1.2.5版本可用，之后版本都不行

**Comment by FlySelfLog** [comment]
> 实测1.2.5版本可用，之后版本都不行

1.3.2已经可以使用了
