### ISSUE TITLE
建议下载的视频文件名前面加上原列表序号

### ISSUE THREAD

**Issue by wheatMr** [FlySelfLog/downkyi#10]
下载的视频文件名前面加上序号与原视频目录列表就可以保持一致了。
![image](https://user-images.githubusercontent.com/12541828/105005877-d7e6db80-5a70-11eb-948c-ad81236f9843.png)

**Comment by FlySelfLog** [comment]
可以设置下载文件增加序号

**Comment by wheatMr** [comment]
感谢！
