### ISSUE TITLE
您好，有4个小期待+2个问题

### ISSUE THREAD

**Issue by Ariesthirteen** [FlySelfLog/downkyi#19]
几个小期待：
1、希望在地址输入栏的右侧增加一个搜索按钮，能用鼠标点击来搜索。
2、希望增加一键切换所有分p视频的分辨率画质的选项/按钮。比如：我要下载一套课程有130P，默认最高画质1080p，我必须下载观看，但硬盘空间实在不够了，此时我就迫切需要选择720p甚至更低的画质来下载。还有些课程，没有字幕，也没有在线讲义，只有授课老师出现在画面上，这种视频720p就足以看清，还有其它原因等等。但目前的设置，虽然每一P画质可以手动选择，可130p逐项手动切换分辨率操作会非常繁琐很费时间，所以基于这类需求，希望能增加一个统一切换画质的选项/按钮。
3、启用视频编号后，文件名前的序号为1_2_3_N_……希望能变更为1.2.3.4.5.N.
4、希望复制视频地址后能自动弹出下载页面。

使用中发现的问题：
1、不知道哪方面原因，我解析每1P画质的速度非常慢，平均大概3-5秒才能解析出来一个P。软件版本是最新1.3.4。
自用平台：AMD3600+16g 高频3200+显卡1660s+B450max迫击炮+500g西数M.2黑盘SN750+联通100M光纤
2、我登录自己的帐号后并没有显示出新增的up主频道列表展示和投稿视频列表展示，更新的视频分区也没有。

**Comment by FlySelfLog** [comment]
依次回复：
1、可以考虑，以后更新
2、在设置中是可以统一设置最高画质的
3、这个每个人的命名习惯都不同，改来改去太麻烦，pass
4、在做了

问题回复：
1、这个和B站服务器的响应速度有关，没有使用多线程同时解析是担心短时间大量访问被封ip
2、主页搜索别的up主的空间url，可以看到投稿列表和频道列表，下个版本会增加其他页面点击up主头像进入up主空间的入口
