### ISSUE TITLE
大大，正在下载中的视频想取消下载应该怎么整啊？

### ISSUE THREAD

**Issue by xiaowu10269** [FlySelfLog/downkyi#2]
如题，我下一个有100多P视频的时候有几P没下载下来，然后就重新下载了，然后我发现已下载记录没有了，100多P都得重新下，然后我没找到取消下载的地方

**Comment by FlySelfLog** [comment]
v1.3.0 beta开始有下载历史记录，也增加了暂停删除按钮，不过这个版本存在问题，等下个版本吧

**Comment by FlySelfLog** [comment]
1.3.2 beta 已解决此问题
