### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by Ra1sin** [FlySelfLog/downkyi#20]
一，取消下载FLV视频后转码为MP4，下载下来的依然为MP4。

二，视频封面建议设置为视频同名，目前的命名策略为Cover，在不同地址的多个视频一起下载时，只能下载成功第一个视频封面，后完成的视频，无法下载封面。

**Comment by FlySelfLog** [comment]
1、测试后发现没有问题，因为B站自身有flv和mp4两种格式，“下载FLV视频后转码为MP4”是指当下载的为flv格式时，将flv文件转码为mp4，大部分视频本来就是mp4
2、设置中有“为不同视频创建文件夹”，勾选上可避免此问题
