### ISSUE TITLE
期待能提供个选项“在下载视频的同时下载弹幕”

### ISSUE THREAD

**Issue by pp11pp1122** [FlySelfLog/downkyi#24]
因为本身看B站视频喜欢带着弹幕观看，之前用过的you-get也有这样类似下载视频同时下载弹幕的功能，但用起来没有大佬写的这个好用，自己下载弹幕的话又需要一个一个视频点进去下载，所以期待能添加这一功能

**Comment by John-Smith-2020** [comment]
附议，这个功能非常便利。

**Comment by FlySelfLog** [comment]
在做了
