### ISSUE TITLE
[bug 2] 部分视频下载卡死，原因不详

### ISSUE THREAD

**Issue by John-Smith-2020** [FlySelfLog/downkyi#26]
以下三个视频一个无法开始，一个下载完成后自动失败，一个开始即失败
https://www.bilibili.com/video/BV1AJ411d7ns
https://www.bilibili.com/video/BV14s411d7QL
https://www.bilibili.com/video/BV1bW411X7wd
网页端使用Bilibili-Evolved插件在不挂代理情况下也无法下载（但可以正常播放），挂代理切换到海外CDN则可下载。非常诡异的bug

**Comment by FlySelfLog** [comment]
BV1AJ411d7ns、BV1bW411X7wd的问题已修复，BV14s411d7QL需在登录的情况下才能获取数据
