### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by gagadsfg** [FlySelfLog/downkyi#28]
1.3.5 按照正常操作扫码登录成功后跳转到主页后，右上角仍显示为未登录的状态，解析也是未登录时的内容。但是重新打开软件后右上角才显示出登录后的状态(算是临时解决办法吧)，可以解析登录后的内容。希望可以解决一下这个问题，1.3.3没有这个情况。

**Comment by FlySelfLog** [comment]
下次更新修复
