### ISSUE TITLE
请问可以支持一个新功能吗？

### ISSUE THREAD

**Issue by FuYang001** [FlySelfLog/downkyi#3]
请问可以添加这么一个功能吗？
获取up主所有发布的视频并下载，就是输入主页地址就可以全部下载的那种。请问可以做吗qwq

**Comment by FlySelfLog** [comment]
在做了在做了

**Comment by FuYang001** [comment]
> 在做了在做了

感谢作者qwq，请问有联系方式吗，我给您发红包~

**Comment by FlySelfLog** [comment]
> > 在做了在做了
> 
> 感谢作者qwq，请问有联系方式吗，我给您发红包~

    readme里有二维码

**Comment by FuYang001** [comment]
> > > 在做了在做了
> > 
> > 
> > 感谢作者qwq，请问有联系方式吗，我给您发红包~
> 
> ```
> readme里有二维码
> ```

嗯嗯我发了，可以加个微信吗，这样我也可以更方便联系到您qwq

**Comment by FlySelfLog** [comment]
> > > > 在做了在做了
> > > 
> > > 
> > > 感谢作者qwq，请问有联系方式吗，我给您发红包~
> > 
> > ```
> > readme里有二维码
> > ```
> 
> 嗯嗯我发了，可以加个微信吗，这样我也可以更方便联系到您qwq

qq 1432593898
