### ISSUE TITLE
您好，【下载管理】项下的【已下载】列表中，能否让最近一次下载的视频排在最前面，按时间倒序排列？或者按视频序号排列？

### ISSUE THREAD

**Issue by Ariesthirteen** [FlySelfLog/downkyi#33]
您好，【下载管理】项下的【已下载】列表中，能否让最近一次下载的视频排在最前面，按时间倒序排列？或者按视频序号排列？这样依次类推。
比如，10：00下载了视频1，10：03下载了视频2，10：05下载了视频3，那么让10：05的视频3排在列表的第1位，视频2排在第2位，视频1排在第3位。
或者，能按所下载视频的序号排列也是好的，比如1、2、3、这样排下来。
（这样比较好找，如果既不是按序号排练，也不是按时间排列，也不能直接搜索文件名的话，一旦下载视频多了，想找到特定的视频就比较繁琐和困难，倒序排列或者按序号排列能让我快速定位到文件名，打开其所在位置）

**Comment by kulkatt** [comment]
是啊，我为什么每次都要从几个月前下载的视频看起？
