### ISSUE TITLE
登陆大会员账号去解析电影,结果也只有6分钟长度啊?能解决不

### ISSUE THREAD

**Issue by 0772boy** [FlySelfLog/downkyi#38]
https://www.bilibili.com/bangumi/play/ss37947
比如这样的,解析出来清晰度是各种都有,但是视频长度就只有6分钟
求翻牌

**Comment by FlySelfLog** [comment]
这部电影是需要付费观看的，大会员也需要，你能观看的视频软件才能解析，所以不是软件的问题
