### ISSUE TITLE
部分视频下载后和原视频封面不一致

### ISSUE THREAD

**Issue by biue123** [FlySelfLog/downkyi#47]
部分视频下载后和原视频封面不一致，会生成一个Cover.jpg

**Comment by FlySelfLog** [comment]
比如说？

**Comment by biue123** [comment]
https://www.bilibili.com/video/BV1c54y1W77q
收藏夹中的
操作详情：https://ws28.cn/f/4xzpt76gfqg

**Comment by FlySelfLog** [comment]
这个没有问题，封面是B站上的那个，不是视频的第一帧，如果想要视频的第一帧，很多播放器都能提取
