### ISSUE TITLE
不知道为什么这两天一直闪退

### ISSUE THREAD

**Issue by xiaowu10269** [FlySelfLog/downkyi#5]
1.2.5 beta和最新的1.3.2 beta我都试了，应该不是版本的问题；下载的时候全选和单选几个也是一样的；重启我也试过，没有用，不知道到底怎么了。之前下载视频都好用的

**Comment by FlySelfLog** [comment]
我这里用v1.3.2 beta测试没有问题。闪退时具体情况是什么，某个视频还是所有视频？解析时还是下载时？

**Comment by xiaowu10269** [comment]
应该是解析的时候就闪退了，我看了一下没有下载的时候会有的audio文件

**Comment by xiaowu10269** [comment]
刚刚我想试一下不从收藏里下载，直接通过链接下载，发现解析不出来，出现根据此BV没有找到视频，AV号也不可以

**Comment by xiaowu10269** [comment]
会不会是我这两天下载的视频太多了？从12.30号开始我用这个软件下载收藏夹，大概下载了2500条视频了

**Comment by FlySelfLog** [comment]
从收藏夹下载某个视频，软件闪退；但是通过链接解析不出来，是这样吧？
把视频链接发出来，不然无法测试......

**Comment by xiaowu10269** [comment]
不是具体的某条视频，我试了一下用一个新账号解析视频，是可以解析出来的，应该是我的账号出问题了

**Comment by xiaowu10269** [comment]
可以加一个微信吗？
