### ISSUE TITLE
最新1.3.7  根据uid进入， 要么全选视频；要么只能选择一个，我选择第二个视频的时候，第一个视频就取消了。

### ISSUE THREAD

**Issue by jjy7pspsjl** [FlySelfLog/downkyi#54]
最新1.3.7  根据uid进入， 要么全选视频；要么只能选择一个，我选择第二个视频的时候，第一个视频就取消了。

**Comment by FlySelfLog** [comment]
按住ctrl在多选

**Comment by jjy7pspsjl** [comment]
了解




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FlySelfLog/downkyi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 下午2:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FlySelfLog/downkyi] 最新1.3.7  根据uid进入， 要么全选视频；要么只能选择一个，我选择第二个视频的时候，第一个视频就取消了。 (#54)





 
按住ctrl再多选
