### ISSUE TITLE
下载全是失败！

### ISSUE THREAD

**Issue by saicj1** [FlySelfLog/downkyi#57]
BV1Y4411e7Yh
什么原因

![1](https://user-images.githubusercontent.com/80991902/113160053-a76bac80-922c-11eb-998c-fbb33229b85a.png)

![2](https://user-images.githubusercontent.com/80991902/113160181-c8cc9880-922c-11eb-913e-054164509cec.png)

**Comment by FlySelfLog** [comment]
我这里测试没有问题，可以正常下载

![Snipaste_2021-04-01_00-15-08](https://user-images.githubusercontent.com/19290097/113176843-7ec0d280-927f-11eb-9c15-80c5f4b423e3.png)
