### ISSUE TITLE
1.3.7的解除地区限制，怎么不可勾选了

### ISSUE THREAD

**Issue by saicj1** [FlySelfLog/downkyi#59]
鼠标左键玩命的点，方框的勾就是不出现
然退回到1.3.6，却是能勾选的

![1](https://user-images.githubusercontent.com/80991902/113364077-1a1a7c00-9342-11eb-810f-20820c1c4052.png)

**Comment by FlySelfLog** [comment]
解除地区限制失效了，所以禁用了这个选项
