### ISSUE TITLE
有些番劇視頻不能下

### ISSUE THREAD

**Issue by w0853** [FlySelfLog/downkyi#62]
https://www.bilibili.com/bangumi/play/ep313680
https://www.bilibili.com/bangumi/play/ep311858
這兩個網址上去都沒有這2個視頻的下載

**Comment by FlySelfLog** [comment]
![Snipaste_2021-04-17_13-23-05](https://user-images.githubusercontent.com/19290097/115102833-304e4c00-9f80-11eb-8bc3-9742683e564d.png)
我这里测试是可以的

**Comment by w0853** [comment]
https://imgur.com/a/VqVzDpo
請問你那邊有這2個我圈起來的這2個影片嗎(我這邊的軟體沒讀到這2個,26集全出來沒錯但"预告&花絮"沒)

**Comment by FlySelfLog** [comment]
目前暂时只支持正片，有计划加入子视频的解析

**Comment by w0853** [comment]
謝謝
