### ISSUE TITLE
【Bug】当剧集里的集数太多时会直接闪退

### ISSUE THREAD

**Issue by IceWeet** [FlySelfLog/downkyi#63]
闪退原因是我猜测的，具体重现步骤为：复制某个up主的主页进行识别，工具识别成功进去页面后，点击全部视频，然后就闪退了。猜测是视频数量过多导致的。

测试uid：uid193147738

**Comment by tomchang126** [comment]
同樣有遇到這個問題
我是在【肥皂菌】的時候遇到,影片數量216
https://space.bilibili.com/634131

**Comment by FlySelfLog** [comment]
已修复
