### ISSUE TITLE
下载失败后不能即使重试也无法继续下载

### ISSUE THREAD

**Issue by nicholasllj** [FlySelfLog/downkyi#73]
貌似不知道是不是由于网络问题，断开连接后也无法继续下载，然后要删掉任务重新进入改地址解析视频后选中所选的视频才能成功下载
还有为什么每次点击下载都会提问保存路径？
![360截图20210430211440459](https://user-images.githubusercontent.com/72863028/116700512-6fa57f80-a9f9-11eb-8107-653c02dbdbee.png)

![360截图20210430210728578](https://user-images.githubusercontent.com/72863028/116699808-a0d18000-a9f8-11eb-9a20-3d21c1960510.png)

**Comment by shaunmaxman** [comment]
1.下载失败,可能是 一次下载太多被官方 暂时屏蔽了,我等了一段时间自己好了 ;
2.确实存在 每次下载都询问 下载保存位置 有点恼人

**Comment by FlySelfLog** [comment]
是否每次询问下载位置在设置中可以修改
