### ISSUE TITLE
我是会员，能看视频，但是依然下载的视频只有6分钟

### ISSUE THREAD

**Issue by klingw** [FlySelfLog/downkyi#89]
例如地球脉动：https://www.bilibili.com/bangumi/play/ss20302/?from=search&seid=6924195762665287284

**Comment by FlySelfLog** [comment]
![image](https://user-images.githubusercontent.com/19290097/121780876-e1fea780-cbd4-11eb-98c0-54e708e25893.png)
我这里测试没问题
