### ISSUE TITLE
1.2.5 和 1.3.2 均无法解析多 p 列表

### ISSUE THREAD

**Issue by 7eopard** [FlySelfLog/downkyi#9]
链接：https://www.bilibili.com/video/BV1os411h75S

**Comment by FlySelfLog** [comment]
我这里用1.3.2版可以解析出来

**Comment by FlySelfLog** [comment]
![image](https://user-images.githubusercontent.com/19290097/105014670-ab848c80-5a7b-11eb-80a1-810b1ee35366.png)

**Comment by 7eopard** [comment]
感谢！重新安装可以了。
